services:
  auth-service:
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_URL: jdbc:postgresql://postgres:5432/smartmarket
      DB_USERNAME: smartmarket
      DB_PASSWORD: smartmarket
      SPRING_REDIS_HOST: redis

  supermarket-service:
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_URL: jdbc:postgresql://postgres:5432/smartmarket
      DB_USERNAME: smartmarket
      DB_PASSWORD: smartmarket
      SPRING_REDIS_HOST: redis

  product-service:
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_URL: jdbc:postgresql://postgres:5432/smartmarket
      DB_USERNAME: smartmarket
      DB_PASSWORD: smartmarket
      SPRING_REDIS_HOST: redis
