services:
  api-gateway:
    environment:
      SPRING_PROFILES_ACTIVE: local
      AUTH_SERVICE_URL: http://auth-service:8081
      SUPERMARKET_SERVICE_URL: http://supermarket-service:8082
      PRODUCT_SERVICE_URL: http://product-service:8083
      CLIENT_SERVICE_URL: http://client-service:8084
      NOTIFICATION_SERVICE_URL: http://notification-service:8085
      RECOMMENDATION_SERVICE_URL: http://recommendation-service:8086

  auth-service:
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_URL: jdbc:postgresql://postgres:5432/smartmarket
      DB_USERNAME: smartmarket
      DB_PASSWORD: smartmarket

  supermarket-service:
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_URL: jdbc:postgresql://postgres:5432/smartmarket
      DB_USERNAME: smartmarket
      DB_PASSWORD: smartmarket

  product-service:
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_URL: jdbc:postgresql://postgres:5432/smartmarket
      DB_USERNAME: smartmarket
      DB_PASSWORD: smartmarket

  client-service:
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_URL: jdbc:postgresql://postgres:5432/smartmarket
      DB_USERNAME: smartmarket
      DB_PASSWORD: smartmarket

  notification-service:
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_URL: jdbc:postgresql://postgres:5432/smartmarket
      DB_USERNAME: smartmarket
      DB_PASSWORD: smartmarket

  recommendation-service:
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_URL: jdbc:postgresql://postgres:5432/smartmarket
      DB_USERNAME: smartmarket
      DB_PASSWORD: smartmarket
