-- Fix numeric column types from NUMERIC to DOUBLE PRECISION
ALTER TABLE supermercados
    ALTER COLUMN latitude TYPE DOUBLE PRECISION USING latitude::DOUBLE PRECISION,
    ALTER COLUMN longitude TYPE DOUBLE PRECISION USING longitude::DOUBLE PRECISION;
